MAJ des infos sur V&T
etalab/schema-amenagements-cyclables pull request #87
Opened 2024-09-02 15:52 UTC by IdrissaD

Suite à l'échange avec @stephane-pignal, voici une mise à jour de certaines informations obsolètes concernant Vélo & Territoires et ses actions autour du schéma aménagements cyclables.

2024-09-11 13:05 UTC, stephane-pignal commented
👍 @IdrissaD 

**Propositions**
Ligne39 "Outils internes" : Être plus explicit, lesquels ?
Ligne 56 : supprimer le "si elle"
Ligne 57 : remplacer par "publier sur OpenStreetMap afin que Géovélo se charge de la conversion du schéma national et de la publication sur data.gouv.fr"
Ligne 59 : étant donné que c'est un problème récurrent, mettre davantage en valeur le "Nous invitons également les producteurs de données à sélectionner "schéma d'aménagements cyclables" dans la liste déroulante de la section "schema" sur data.gouv.fr lorsqu'ils publieront leurs fichiers."
Ligne 68 : à l'époque ce point a été apparemment évoqué mais reste à discuter (pertinence, faisabilité, ressource)

2024-09-11 15:02 UTC, stephane-pignal commented on README.md
> -- demander à Géovélo de convertir leurs données vers le schéma national si elle
"si elle" à supprimer

2024-09-11 15:04 UTC, stephane-pignal commented on README.md
>  Nous préconisons aux producteurs de données de publier leurs fichiers avec la règle de nommage suivante : `amenagementcyclable_nom.geojson` avec nom étant le nom de la collectivité productrice des do
Proposition de reformulation du texte "publier sur OpenStreetMap afin que Géovélo se charge de la conversion du schéma national et de la publication sur data.gouv.fr"

2024-09-11 15:10 UTC, stephane-pignal commented on README.md
>  - une base nationale regroupant les données publiées par les collectivités sur data.gouv.fr ;
à l'époque ce point a été apparemment évoqué mais reste à discuter (pertinence, faisabilité, ressource)

2024-09-23 08:39 UTC, IdrissaD commented on README.md
>  - une base nationale regroupant les données publiées par les collectivités sur data.gouv.fr ;
Tout à fait, je ne l'ai pas changé car ce projet n'est pas sous notre responsabilité, mais si cette base n'existe actuellement pas, j'ai un doute sur la pertinence de continuer à la mentionner dans la documentation.

2024-09-23 08:51 UTC, IdrissaD commented on README.md
>  - des outils internes ;
Je crois que "outils internes" dans ce contexte signifie "outils internes aux producteurs de données", ce qui ne permet pas d'être explicite puisque cela dépend de chaque producteur. Mais peut-être que cette mention est inutile, chaque producteur sachant bien qu'il peut saisir ses données sur ses propres outils ?

D'ailleurs les outils de V&T comme le gabarit et le script SQL ne sont pour moi pas des outils externes, mais des outils d'aide à la saisie interne.

On pourrait reformuler en
```
Les producteurs peuvent saisir leurs données sur :
- leurs logiciels internes, aidés par les outils développés par Vélo & Territoires, à savoir : 
   - gabarit
   - script SQL
- la base de données OpenStreetMap (OSM).
```

Je trouve que ce serait plus clair de cette manière.

2024-09-23 08:57 UTC, IdrissaD commented on README.md
> -- demander à Géovélo de convertir leurs données vers le schéma national si elle
Déjà corrigé, la ligne en question est en rouge.

2024-09-24 09:00 UTC, Brewennn commented on README.md
>  - une base nationale regroupant les données publiées par les collectivités sur data.gouv.fr ;
Je pense qu'on peut supprimer cette mention car pour l'instant ce n'est pas d’actualité, si c'est ok pour @stephane-pignal.

2024-09-27 07:20 UTC, Brewennn requested changes
Lignes 65 -66 : supprimer la mention "- une base nationale regroupant les données publiées par les collectivités sur data.gouv.fr ;". En conséquence changer la mention "trois bases" par "deux bases".

2024-09-27 07:34 UTC, Brewennn approved these changes

2024-10-03 11:32 UTC, stephane-pignal commented
Validation des modifs côté V&T et PAN

2024-10-04 09:42 UTC, merged